package com.hailan.HaiLanPrint.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "LOCATION".
 */
public class Location {

    private String EnglishName;
    private Boolean IsCity;
    private Boolean IsHot;
    private Boolean IsValid;
    private Long LocationCode;
    private Long LocationID;
    private String LocationName;
    private Float LocationX;
    private Float LocationY;
    private Long ParentID;

    public Location() {
    }

    public Location(Long LocationID) {
        this.LocationID = LocationID;
    }

    public Location(String EnglishName, Boolean IsCity, Boolean IsHot, Boolean IsValid, Long LocationCode, Long LocationID, String LocationName, Float LocationX, Float LocationY, Long ParentID) {
        this.EnglishName = EnglishName;
        this.IsCity = IsCity;
        this.IsHot = IsHot;
        this.IsValid = IsValid;
        this.LocationCode = LocationCode;
        this.LocationID = LocationID;
        this.LocationName = LocationName;
        this.LocationX = LocationX;
        this.LocationY = LocationY;
        this.ParentID = ParentID;
    }

    public String getEnglishName() {
        return EnglishName;
    }

    public void setEnglishName(String EnglishName) {
        this.EnglishName = EnglishName;
    }

    public Boolean getIsCity() {
        return IsCity;
    }

    public void setIsCity(Boolean IsCity) {
        this.IsCity = IsCity;
    }

    public Boolean getIsHot() {
        return IsHot;
    }

    public void setIsHot(Boolean IsHot) {
        this.IsHot = IsHot;
    }

    public Boolean getIsValid() {
        return IsValid;
    }

    public void setIsValid(Boolean IsValid) {
        this.IsValid = IsValid;
    }

    public Long getLocationCode() {
        return LocationCode;
    }

    public void setLocationCode(Long LocationCode) {
        this.LocationCode = LocationCode;
    }

    public Long getLocationID() {
        return LocationID;
    }

    public void setLocationID(Long LocationID) {
        this.LocationID = LocationID;
    }

    public String getLocationName() {
        return LocationName;
    }

    public void setLocationName(String LocationName) {
        this.LocationName = LocationName;
    }

    public Float getLocationX() {
        return LocationX;
    }

    public void setLocationX(Float LocationX) {
        this.LocationX = LocationX;
    }

    public Float getLocationY() {
        return LocationY;
    }

    public void setLocationY(Float LocationY) {
        this.LocationY = LocationY;
    }

    public Long getParentID() {
        return ParentID;
    }

    public void setParentID(Long ParentID) {
        this.ParentID = ParentID;
    }

}
